// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'edit_with_your_api_key',
    appId: 'edit_with_your_app_id',
    messagingSenderId: '249160825366',
    projectId: 'edit_with_your_project_id',
    authDomain: 'edit_with_your_project_domain',
    storageBucket: 'edit_with_your_project_domain',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'edit_with_your_api_key',
    appId: 'edit_with_your_app_id',
    messagingSenderId: '249160825366',
    projectId: 'edit_with_your_project_id',
    storageBucket: 'edit_with_your_project_domain',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'edit_with_your_api_key',
    appId: 'edit_with_your_app_id',
    messagingSenderId: '249160825366',
    projectId: 'edit_with_your_project_id',
    storageBucket: 'edit_with_your_project_domain',
    iosBundleId: 'com.example.assetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'edit_with_your_api_key',
    appId: 'edit_with_your_app_id',
    messagingSenderId: '249160825366',
    projectId: 'edit_with_your_project_id',
    storageBucket: 'edit_with_your_project_domain',
    iosBundleId: 'com.example.assetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'edit_with_your_api_key',
    appId: 'edit_with_your_app_id',
    messagingSenderId: '249160825366',
    projectId: 'edit_with_your_project_id',
    authDomain: 'edit_with_your_project_domain',
    storageBucket: 'edit_with_your_project_domain',
  );
}
