// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6n7UxiGuuBPAitxM7c1loNXKBP4J-fc',
    appId: '1:249160825366:web:c35904035bb02fc0089337',
    messagingSenderId: '249160825366',
    projectId: 'asset-tracker-b3812',
    authDomain: 'asset-tracker-b3812.firebaseapp.com',
    storageBucket: 'asset-tracker-b3812.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOG-vi7apxSc6cVss1eyaIAFovYCmWWk',
    appId: '1:249160825366:android:9142dcef3511d7e0089337',
    messagingSenderId: '249160825366',
    projectId: 'asset-tracker-b3812',
    storageBucket: 'asset-tracker-b3812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBkL1ErOeJ9Xe1PJs4kjDuf8rAH6im9Yo',
    appId: '1:249160825366:ios:f09f61309fcc9501089337',
    messagingSenderId: '249160825366',
    projectId: 'asset-tracker-b3812',
    storageBucket: 'asset-tracker-b3812.firebasestorage.app',
    iosBundleId: 'com.example.assetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBkL1ErOeJ9Xe1PJs4kjDuf8rAH6im9Yo',
    appId: '1:249160825366:ios:f09f61309fcc9501089337',
    messagingSenderId: '249160825366',
    projectId: 'asset-tracker-b3812',
    storageBucket: 'asset-tracker-b3812.firebasestorage.app',
    iosBundleId: 'com.example.assetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6n7UxiGuuBPAitxM7c1loNXKBP4J-fc',
    appId: '1:249160825366:web:86fc05740072a227089337',
    messagingSenderId: '249160825366',
    projectId: 'asset-tracker-b3812',
    authDomain: 'asset-tracker-b3812.firebaseapp.com',
    storageBucket: 'asset-tracker-b3812.firebasestorage.app',
  );
}
